### ISSUE TITLE
Convert trained model for use with inference with wdv3-jax

### ISSUE THREAD

**Issue by onirhakin** [SmilingWolf/JAX-CV#16]
If i understood correctly JAX-CV is used for training the models, and then wdv3-jax to run the inference no?

I was able to run train some models using the ai-booru dataset because it peeked out in some other issue like https://github.com/SmilingWolf/JAX-CV/issues/11 ( but i realize likely it is not the one you use).

I noticed that the resulting model is not in the same format as the one on hugging face, runned with wdv3-jax, but the files are different.
How can i convert the result from the training to that format?

I was able to run inference with a custom script made by AI, and it shows that my trained model eva02_medium is shit XD, very likely because of how I trained it, i would need advices for that, but maybe is better to ask in another issue.

**Comment by SmilingWolf** [comment]
Yeah I use [orbax-checkpoint](https://github.com/google/orbax) during training, but after all is said and done it's easier to distribute a single msgpack file for end users.

The code I use for conversion is this:

```
from pathlib import Path

import flax
import orbax.checkpoint as ocp

model_path = Path("checkpoints/eva02_large_2024_09_18_19h54m02s").resolve()

orbax_checkpointer = ocp.PyTreeCheckpointer()
checkpoint_manager = ocp.CheckpointManager(
    model_path,
    orbax_checkpointer,
)

latest_epoch = checkpoint_manager.latest_step()
restored = checkpoint_manager.restore(latest_epoch)["model"]

with open("eva02.msgpack", "wb") as f:
    serialize_vars = restored
    whitelist = ["params", "constants"]
    for var_name in list(serialize_vars.keys()):
        if var_name not in whitelist:
            del serialize_vars[var_name]
    model_dict = {"model": serialize_vars}
    data = flax.serialization.msgpack_serialize(model_dict)
    f.write(data)
```

It removes all extra data like optimizer states etc. and only leaves the model weights and constants.

**Comment by onirhakin** [comment]
Thank you so much for the response!

I used that script to convert the model, but i also needed the configurations file and the tags, so made them and modified the inference script to run using the local files. Spent a lot of time on the tags :( and now seems to basically work. 
I also notice the orbax and the msgpack models have slightly different confidences, maybe because of some roundoff or because i runned on on gpu and the other on cpu?
Maybe for my case was just better to run the original orbax model.

By the way, i have a very text-wise long issue open if you have spare time ;) and want to read it, I'm curious of your opinion, sorry if it is not pertinent :(

**Comment by SmilingWolf** [comment]
> maybe because of some roundoff or because i runned on on gpu and the other on cpu?

This is the absolutely most likely reason. Checkpoint vs msgpack is not a factor.
The differences should be small though, somewhere in the order of 1e-4 ~ 1e-5.

**Comment by onirhakin** [comment]
Mhh, it is on the order of 1e-3 and more in some cases, if i remember correctly, but more or less the tags are the same and in the same order except few. So should be mostly fine, on that side.

Thanks!
